/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login-old`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alert` | `/alert`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chemicals` | `/chemicals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/qr-demo` | `/qr-demo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stock-out` | `/stock-out`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/want-view` | `/want-view`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/want` | `/want`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login-old`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alert` | `/alert`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chemicals` | `/chemicals`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/qr-demo` | `/qr-demo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stock-out` | `/stock-out`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/want-view` | `/want-view`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/want` | `/want`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login-old${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alert${`?${string}` | `#${string}` | ''}` | `/alert${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chemicals${`?${string}` | `#${string}` | ''}` | `/chemicals${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/qr-demo${`?${string}` | `#${string}` | ''}` | `/qr-demo${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stock-out${`?${string}` | `#${string}` | ''}` | `/stock-out${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stock${`?${string}` | `#${string}` | ''}` | `/stock${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/want-view${`?${string}` | `#${string}` | ''}` | `/want-view${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/want${`?${string}` | `#${string}` | ''}` | `/want${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login-old`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alert` | `/alert`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chemicals` | `/chemicals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/qr-demo` | `/qr-demo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stock-out` | `/stock-out`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/want-view` | `/want-view`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/want` | `/want`; params?: Router.UnknownInputParams; };
    }
  }
}
